{ "label": "Viewport (layer name)", "value": "viewport" },
{ "label": "Stage (layer name)", "value": "stage" },
{ "label": "Width (px)", "value": "absWidth" },
{ "label": "Height (px)", "value": "absHeight" },
{ "label": "Width (%)", "value": "relWidth" },
{ "label": "Height (%)", "value": "relHeight" },
{ "label": "Maintain aspect ratio (min, max)", "value": "maintainAspectRatio" },
{ "label": "Aspect ratio (float)", "value": "aspectRatio" },
{ "label": "Camera X (px)", "value": "absCameraX" },
{ "label": "Camera Y (px)", "value": "absCameraY" },
{ "label": "Camera X (%)", "value": "relCameraX" },
{ "label": "Camera Y (%)", "value": "relCameraY" },
{ "label": "Camera parallax level (number)", "value": "cameraParallaxLevel" },
{ "label": "Camera move / Max speed (px / s)", "value": "cameraMoveMaxSpeed" },
{ "label": "Camera move / Friction (float)", "value": "cameraMoveFriction" },
{ "label": "Camera move / Method (drag, click, scroll, follow)", "value": "cameraMoveMethod" },
{ "label": "Camera move / Drag radius (px)", "value": "cameraMoveDragRadius" },
{ "label": "Camera move / Click speed (px / s)", "value": "cameraMoveClickSpeed" },
{ "label": "Camera move / Click time (s)", "value": "cameraMoveClickTime" },
{ "label": "Camera move / Click ease (name)", "value": "cameraMoveClickEase" },
{ "label": "Camera move / Scroll speed (px / s)", "value": "cameraMoveScrollSpeed" },
{ "label": "Camera move / Scroll sensitivity (%)", "value": "cameraMoveScrollSensitivity" },
{ "label": "Camera move / X (px)", "value": "cameraMoveX" },
{ "label": "Camera move / Y (px)", "value": "cameraMoveY" },
{ "label": "Camera move / DX (px / s)", "value": "cameraMoveDX" },
{ "label": "Camera move / DY (px / s)", "value": "cameraMoveDY" }