{ "label": "Smoothing?", "value": "smoothing" },
{ "label": "Use hand cursor?", "value": "useHandCursor" },
{ "label": "Trigger pointer events?", "value": "triggerPointerEvents" },
{ "label": "Visible?", "value": "visible" },
{ "label": "Trigger visibility events?", "value": "triggerVisibilityEvents" },
{ "label": "Parallax scale?", "value": "parallaxScale" },
{ "label": "Parallax level (number)", "value": "parallaxLevel" },
{ "label": "Alpha (%)", "value": "alpha" },
{ "label": "X (%)", "value": "relX" },
{ "label": "Y (%)", "value": "relY" },
{ "label": "X (px)", "value": "absX" },
{ "label": "Y (px)", "value": "absY" },
{ "label": "Self relative X (%)", "value": "selfRelX" },
{ "label": "Self relative Y (%)", "value": "selfRelY" },
{ "label": "Reference X (%)", "value": "relReferenceX" },
{ "label": "Reference Y (%)", "value": "relReferenceY" },
{ "label": "Reference X (px)", "value": "absReferenceX" },
{ "label": "Reference Y (px)", "value": "absReferenceY" },
{ "label": "Width (%)", "value": "relWidth" },
{ "label": "Height (%)", "value": "relHeight" },
{ "label": "Width (px)", "value": "absWidth" },
{ "label": "Height (px)", "value": "absHeight" },
{ "label": "Scale X (%)", "value": "scaleX" },
{ "label": "Scale Y (%)", "value": "scaleY" },
{ "label": "Aspect ratio (number)", "value": "aspectRatio" },
{ "label": "Maintain aspect ratio (min/max)", "value": "maintainAspectRatio" },
{ "label": "Rotation (degrees)", "value": "rotation" },
{ "label": "Reference frame (layer name)", "value": "refFrame" },
{ "label": "Reference frame / Anchor X?", "value": "refFrameAnchorX" },
{ "label": "Reference frame / Anchor Y?", "value": "refFrameAnchorY" },
{ "label": "Reference frame / Anchor parallax level?", "value": "refFrameAnchorParallaxLevel" },
{ "label": "Reference frame / Anchor scaleX?", "value": "refFrameAnchorScaleX" },
{ "label": "Reference frame / Anchor scaleY?", "value": "refFrameAnchorScaleY" },
{ "label": "Reference frame / Anchor rotation?", "value": "refFrameAnchorRotation" },
{ "label": "Reference frame / Anchor alpha?", "value": "refFrameAnchorAlpha" },
{ "label": "Reference frame / X (%)", "value": "refFrameRelX" },
{ "label": "Reference frame / Y (%)", "value": "refFrameRelY" },
{ "label": "Reference frame / X (px)", "value": "refFrameAbsX" },
{ "label": "Reference frame / Y (px)", "value": "refFrameAbsY" },
{ "label": "Reference frame / Self relative X (%)", "value": "refFrameSelfRelX" },
{ "label": "Reference frame / Self relative Y (%)", "value": "refFrameSelfRelY" },
{ "label": "Reference frame / Width (%)", "value": "refFrameRelWidth" },
{ "label": "Reference frame / Height (%)", "value": "refFrameRelHeight" },
{ "label": "Reference frame / Target width (%)", "value": "refFrameRelTargetWidth" },
{ "label": "Reference frame / Target height (%)", "value": "refFrameRelTargetHeight" },
{ "label": "Move / Method (drag, click, follow)", "value": "moveMethod" },
{ "label": "Move / Max speed (px / s)", "value": "moveMaxSpeed" },
{ "label": "Move / Friction (float)", "value": "moveFriction" },
{ "label": "Move / Click speed (px / s)", "value": "moveClickSpeed" },
{ "label": "Move / Click time (s)", "value": "moveClickTime" },
{ "label": "Move / Click ease (name)", "value": "moveClickEase" },
{ "label": "Move / Follow time (s)", "value": "moveFollowTime" },
{ "label": "Move / X (px)", "value": "moveX" },
{ "label": "Move / Y (px)", "value": "moveY" },
{ "label": "Move / DX (px / s)", "value": "moveDX" },
{ "label": "Move / DY (px / s)", "value": "moveDY" },
{ "label": "Mask", "value": "mask" }