{ "label": "Trigger mouse events?", "value": "triggerMouseEvents" },
{ "label": "Trigger visibility events?", "value": "triggerVisibilityEvents" },
{ "label": "Trigger collision events?", "value": "triggerCollisionEvents" },
{ "label": "Draggable?", "value": "draggable" },
{ "label": "Use hand cursor?", "value": "useHandCursor" },
{ "label": "Smoothing?", "value": "smoothing" },
{ "label": "Visible?", "value": "visible" },
{ "label": "Parallax scale?", "value": "parallaxScale" },
{ "label": "Parallax level", "value": "parallaxLevel" },
{ "label": "Alpha (%)", "value": "alpha" },
{ "label": "Relative X (%)", "value": "relX" },
{ "label": "Relative Y (%)", "value": "relY" },
{ "label": "Absolute X (px)", "value": "absX" },
{ "label": "Absolute Y (px)", "value": "absY" },
{ "label": "Self relative X (%)", "value": "selfRelX" },
{ "label": "Self relative Y (%)", "value": "selfRelY" },
{ "label": "Relative reference X (%)", "value": "relReferenceX" },
{ "label": "Relative reference Y (%)", "value": "relReferenceY" },
{ "label": "Absolute reference X (px)", "value": "absReferenceX" },
{ "label": "Absolute reference Y (px)", "value": "absReferenceY" },
{ "label": "Relative width (%)", "value": "relWidth" },
{ "label": "Relative height (%)", "value": "relHeight" },
{ "label": "Absolute width (px)", "value": "absWidth" },
{ "label": "Absolute height (px)", "value": "absHeight" },
{ "label": "Scale X (%)", "value": "scaleX" },
{ "label": "Scale Y (%)", "value": "scaleY" },
{ "label": "Aspect ratio", "value": "aspectRatio" },
{ "label": "Maintain aspect ratio (min/max)", "value": "maintainAspectRatio" },
{ "label": "Rotation (degrees)", "value": "rotation" },
{ "label": "Reference frame (layer name)", "value": "refFrame" },
{ "label": "Reference frame / Anchor X?", "value": "refFrameAnchorX" },
{ "label": "Reference frame / Anchor Y?", "value": "refFrameAnchorY" },
{ "label": "Reference frame / Anchor parallax level?", "value": "refFrameAnchorParallaxLevel" },
{ "label": "Reference frame / Anchor scaleX?", "value": "refFrameAnchorScaleX" },
{ "label": "Reference frame / Anchor scaleY?", "value": "refFrameAnchorScaleY" },
{ "label": "Reference frame / Anchor rotation?", "value": "refFrameAnchorRotation" },
{ "label": "Reference frame / Anchor alpha?", "value": "refFrameAnchorAlpha" },
{ "label": "Reference frame / Absolute X (px)", "value": "refFrameAbsX" },
{ "label": "Reference frame / Absolute Y (px)", "value": "refFrameAbsY" },
{ "label": "Reference frame / Relative X (%)", "value": "refFrameRelX" },
{ "label": "Reference frame / Relative Y (%)", "value": "refFrameRelY" },
{ "label": "Reference frame / Self relative X (%)", "value": "refFrameSelfRelX" },
{ "label": "Reference frame / Self relative Y (%)", "value": "refFrameSelfRelY" },
{ "label": "Reference frame / Relative width (%)", "value": "refFrameRelWidth" },
{ "label": "Reference frame / Relative height (%)", "value": "refFrameRelHeight" },
{ "label": "Reference frame / Relative target width (%)", "value": "refFrameRelTargetWidth" },
{ "label": "Reference frame / Relative target height (%)", "value": "refFrameRelTargetHeight" },
{ "label": "Mask", "value": "mask" }