{ "label": "Width (px)", "value": "absWidth" },
{ "label": "Height (px)", "value": "absHeight" },
{ "label": "Width (%)", "value": "relWidth" },
{ "label": "Height (%)", "value": "relHeight" },
{ "label": "Maintain aspect ratio (min, max)", "value": "maintainAspectRatio" },
{ "label": "Aspect ratio (float)", "value": "aspectRatio" },
{ "label": "Camera X (%)", "value": "relCameraX" },
{ "label": "Camera Y (%)", "value": "relCameraY" },
{ "label": "Camera parallax level (float)", "value": "cameraParallaxLevel" },
{ "label": "Camera movement method (drag, select, scroll, follow)", "value": "cameraMovementMethod" },
{ "label": "Camera drag radius (px)", "value": "cameraDragRadius" },
{ "label": "Camera drag max speed (px / s)", "value": "cameraDragMaxSpeed" },
{ "label": "Camera friction (float)", "value": "cameraFriction" },
{ "label": "Camera scroll speed (px / s)", "value": "cameraScrollSpeed" },
{ "label": "Camera scroll sensitivity (%)", "value": "cameraScrollSensitivity" }
